In [ ]:
# paddlepaddle==2.3
# Jupyter Notebook
# Python编程
# ML、DL理论知识

# ML
监督学习
两步:训练 + 预测
确定模型参数w
模型有效的基本条件是能够拟合已知的样本
损失函数（损失Loss）：衡量模型预测值和真实值差距的评价函数
模型假设、评价函数（损失/优化目标）和优化算法是构成模型的三个关键要素
学习的本质是“参数估计”

# DL
两者在理论结构上是一致的，即：模型假设、评价函数和优化算法，其根本差别在于假设的复杂度。
神经网络
神经网络基本单元——感知机
人工神经网络包括多个神经网络层，如：卷积层、全连接层、LSTM等，每一层又包括很多神经元，超过三层的非线性神经网络都可以被称为深度神经网络
神经元： 神经网络中每个节点称为神经元，由两部分组成：
- 加权和：将所有输入加权求和。
- 非线性变换（激活函数）：加权和的结果经过一个非线性函数变换，让神经元计算具备非线性的能力。

神经网络的基本概念（如神经元、多层连接、前向计算、计算图）
模型结构三要素（模型假设、评价函数和优化算法）

# 波士顿房价预测

In [ ]:
# Numpy
# 多因素
# 预测问题：回归（连续的实数值） + 分类（离散的标签）
# 线性回归模型：权重和偏置 使用均方误差作为损失函数（Loss）

In [4]:
# 数据处理
'''
数据导入、数据形状变换、数据集划分、数据归一化处理和封装load data函数。
'''
# 读入数据
import numpy as np
import json

datafile = './work/housing.data'
data = np.fromfile(datafile,sep=' ')
data

array([6.320e-03, 1.800e+01, 2.310e+00, ..., 3.969e+02, 7.880e+00,
       1.190e+01])

In [5]:
# 数据形状变换
feature_names = [ 'CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE','DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV' ]
feature_num = len(feature_names)
#对原始数据做reshape，变成N x 14的形式
data= data.reshape([data.shape[0] // feature_num,feature_num])

x = data[0]
print(x.shape)
x

(14,)


array([6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
       6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
       4.980e+00, 2.400e+01])

In [7]:
# 数据集划分
# 训练集 测试集
# 训练集用于确定模型的参数，测试集用于评判模型的效果
ratio = 0.8
offset = int(data.shape[0] * ratio)
training_data, test_data = data[:offset], data[offset:]
training_data.shape

(404, 14)

In [11]:
# 数据归一化处理
# 对每个特征进行归一化处理，使得每个特征的取值缩放到0~1之间。

#计算train数据集的最大值、最小值
maximums,minimums = training_data.max(axis=0),training_data.min(axis=0)

# 对数据进行归一化处理
for i in range(feature_num):
    data[:,i] = (data[:,i]-minimums[i]/(maximums[i]-minimums[i]))

data

array([[6.10928046e-03, 1.80000000e+01, 2.25736239e+00, ...,
        3.96250661e+02, 4.84070350e+00, 2.36740192e+01],
       [2.70992805e-02, 0.00000000e+00, 7.01736239e+00, ...,
        3.96250661e+02, 9.00070350e+00, 2.12740192e+01],
       [2.70792805e-02, 0.00000000e+00, 7.01736239e+00, ...,
        3.92180661e+02, 3.89070350e+00, 3.43740192e+01],
       ...,
       [6.05492805e-02, 0.00000000e+00, 1.18773624e+01, ...,
        3.96250661e+02, 5.50070350e+00, 2.35740192e+01],
       [1.09379280e-01, 0.00000000e+00, 1.18773624e+01, ...,
        3.92800661e+02, 6.34070350e+00, 2.16740192e+01],
       [4.71992805e-02, 0.00000000e+00, 1.18773624e+01, ...,
        3.96250661e+02, 7.74070350e+00, 1.15740192e+01]])